# Generated by Django 5.2.3 on 2025-06-13 06:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThietBi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thiet_bi', models.CharField(max_length=255, verbose_name='Tên Thiết Bị')),
                ('ngay_nhap', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày Nhập')),
                ('ngay_het_han', models.DateField(blank=True, null=True, verbose_name='Ngày Hết Hạn')),
                ('don_vi_tinh', models.CharField(max_length=50, verbose_name='Đơn Vị Tính')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi Chú Chi Tiết')),
                ('nguoi_nhap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thiet_bis_nhap', to=settings.AUTH_USER_MODEL, verbose_name='Người Nhập')),
            ],
            options={
                'verbose_name': 'Thiết Bị',
                'verbose_name_plural': 'Thiết Bị',
                'ordering': ['-ngay_nhap'],
            },
        ),
    ]
