# Generated by Django 5.2.3 on 2025-06-16 02:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkcentral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên Site')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Người liên hệ')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Các Site',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='Số Phòng/Tên Phòng')),
                ('room_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại Phòng')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Sức chứa')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='gkcentral.site', verbose_name='Thuộc Site')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Các Phòng',
                'ordering': ['site__name', 'room_number'],
                'unique_together': {('site', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Mô tả sửa chữa')),
                ('maintenance_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày sửa chữa')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chi phí (VNĐ)')),
                ('performed_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thực hiện bởi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú thêm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Người ghi nhận')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='gkcentral.room', verbose_name='Phòng liên quan')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='gkcentral.site', verbose_name='Site liên quan')),
            ],
            options={
                'verbose_name': 'Bản ghi sửa chữa',
                'verbose_name_plural': 'Lịch sử sửa chữa',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.DeleteModel(
            name='ThietBi',
        ),
    ]
